# -----------------------------------------------------
# Github actions part 1
# Ustos: Denis Astahov
# Shogird: Sh 
# 2022yil
# ------------------------------------------------------
name: My Githubactions-Basics
env:
  APPLICATION_NAME   : "MyFlask"
  DEPLOY_PACKAGE_NAME: "flask-deploy-ver-${{ github.sha }}"

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
 

jobs:
  
  my-testing:
    runs-on: ubuntu-latest

  # Steps 
    steps: 
    - name: Print hello message 
      run : echo "Hello World from Testing job"
      
    - name: Execute few commands 
      run:  |
        echo "hello message1"
        echo "hello message2"
        echo "Application name:${{  env.APPLICATION_NAME }}"
    - name: List current folder
      run: ls -la
          
  my_deploy:
    runs-on: ubuntu-latest
    needs: [my-testing]  
    steps:
    - name: Print hello message 
      run : echo "Hello World from Deploy job "
    
    - name: Printing Hello message in Deploy 
      run: echo "Deploy_package_name is ${{  env.DEPLOY_PACKAGE_NAME }}"
